### ISSUE TITLE
add text filter/mask for, erm, NSFW tweets

### ISSUE THREAD

**Issue by laurenancona** [laurenancona/twimoji#1]
somewhere in the R script, add a text 'filter' function that either masks vowels in NSFW words with `*` or replace entire words with a value

**Comment by ctufts** [comment]
Why the need for a NSFW filter?

**Comment by laurenancona** [comment]
Presenting on this in public & I might include popups with tweet text in the map, which will be publicly viewable. I don't want to alter the data to exclude tweets altogether, but some of the content might be jarring if you're perusing this fluffy little project at work someday.
